### ISSUE TITLE
[Bug Report] Unitree Actuators can't be spawned

### ISSUE THREAD

**Issue by CAI23sbP** [isaac-sim/IsaacLab#4467]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

When using ArticulationCfg with sim_utils.MultiUsdFileCfg to spawn different Unitree robots (A1 and Go2) across vectorized environments, the simulation crashes during env.reset() with a CUDA device-side assert / index out of bounds error.

The same pattern works as expected for ANYbotics ANYmal robots (B/C/D) in the IsaacLab documentation example, where each env can spawn a different robot variant. However, for Unitree A1 and Go2, spawning via MultiUsdFileCfg causes a failure before training starts.

### Steps to reproduce

```
# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from isaaclab.utils import configclass

from .rough_env_cfg import UnitreeGo2RoughEnvCfg
from isaaclab_assets.robots.unitree import UNITREE_GO2_CFG, UNITREE_A1_CFG  , GO1_ACTUATOR_CFG# isort: skip
from isaaclab_assets.robots.anymal import ANYDRIVE_3_LSTM_ACTUATOR_CFG
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR, ISAACLAB_NUCLEUS_DIR
import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg
from isaaclab.actuators import DCMotorCfg

@configclass
class UnitreeGo2FlatEnvCfg(UnitreeGo2RoughEnvCfg):
    def __post_init__(self):
        # post init of parent
        super().__post_init__()
        self.scene.replicate_physics = False
        self.scene.robot = ArticulationCfg(
                prim_path="/World/envs/env_.*/Robot",
                spawn=sim_utils.MultiUsdFileCfg(
                    usd_path=[
                        f"{ISAACLAB_NUCLEUS_DIR}/Robots/Unitree/A1/a1.usd",
                        f"{ISAACLAB_NUCLEUS_DIR}/Robots/Unitree/Go2/go2.usd",
                    ],
                    random_choice=False,
                    rigid_props=sim_utils.RigidBodyPropertiesCfg(
                        disable_gravity=False,
                        retain_accelerations=False,
                        linear_damping=0.0,
                        angular_damping=0.0,
                        max_linear_velocity=1000.0,
                        max_angular_velocity=1000.0,
                        max_depenetration_velocity=1.0,
                    ),
                    articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                        enabled_self_collisions=True, solver_position_iteration_count=4, solver_velocity_iteration_count=0
                    ),
                    activate_contact_sensors=True,
                ),
                init_state=ArticulationCfg.InitialStateCfg(
                    pos=(0.0, 0.0, 0.6),
                    joint_pos={
                    ".*L_hip_joint": 0.1,
                    ".*R_hip_joint": -0.1,
                    "F[L,R]_thigh_joint": 0.8,
                    "R[L,R]_thigh_joint": 1.0,
                    ".*_calf_joint": -1.5,
                    },
                ),
                actuators={
                    "base_legs": DCMotorCfg(
                        joint_names_expr=[".*_hip_joint", ".*_thigh_joint", ".*_calf_joint"],
                        effort_limit=33.5,
                        saturation_effort=33.5,
                        velocity_limit=21.0,
                        stiffness=25.0,
                        damping=0.5,
                        friction=0.0,
                    )
                }
            )

        # override rewards
        self.rewards.flat_orientation_l2.weight = -2.5
        # self.rewards.feet_air_time.weight = 0.25

        # change terrain to flat
        self.scene.terrain.terrain_type = "plane"
        self.scene.terrain.terrain_generator = None
        # no height scan
        # self.scene.height_scanner = None
        # self.observations.policy.height_scan = None
        # no terrain curriculum
        self.curriculum.terrain_levels = None


class UnitreeGo2FlatEnvCfg_PLAY(UnitreeGo2FlatEnvCfg):
    def __post_init__(self) -> None:
        # post init of parent
        super().__post_init__()

        # make a smaller scene for play
        self.scene.num_envs = 50
        self.scene.env_spacing = 2.5
        # disable randomization for play
        self.observations.policy.enable_corruption = False
        # remove random pushing event
        self.events.base_external_force_torque = None
        self.events.push_robot = None

```

### Observed error 

```
  File "/home/cai/isaac_ws/src/IsaacLab/source/isaaclab/isaaclab/assets/articulation/articulation.py", line 181, in reset
    self._external_torque_b[env_ids] = 0.0
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

### System Info

Describe the characteristic of your environment:

- Commit: v2.1.0
- Isaac Sim Version: 4.5
- OS: Ubuntu 22.04
- GPU: RTX 5000 Ada
- CUDA: 13.0
- GPU Driver: 580.95.05

### Additional context

Reference: works for ANYmal in [IsaacLab docs
](https://isaac-sim.github.io/IsaacLab/main/source/how-to/multi_asset_spawning.html#spawning-different-assets-under-the-same-prim-path)
```
robot: ArticulationCfg = ArticulationCfg(
    prim_path="/World/envs/env_.*/Robot",
    spawn=sim_utils.MultiUsdFileCfg(
        usd_path=[
            f"{ISAACLAB_NUCLEUS_DIR}/Robots/ANYbotics/ANYmal-C/anymal_c.usd",
            f"{ISAACLAB_NUCLEUS_DIR}/Robots/ANYbotics/ANYmal-D/anymal_d.usd",
        ],
        random_choice=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True, solver_position_iteration_count=4, solver_velocity_iteration_count=0
        ),
        activate_contact_sensors=True,
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.6),
        joint_pos={
            ".*HAA": 0.0,  # all HAA
            ".*F_HFE": 0.4,  # both front HFE
            ".*H_HFE": -0.4,  # both hind HFE
            ".*F_KFE": -0.8,  # both front KFE
            ".*H_KFE": 0.8,  # both hind KFE
        },
    ),
    actuators={"legs": ANYDRIVE_3_LSTM_ACTUATOR_CFG},
)
```

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Spawning Unitree A1 and Go2 across envs via MultiUsdFileCfg does not crash
- [ ] Documentation clarifies whether MultiUsdFileCfg supports mixing articulations with different DOF/joint structures; if not supported, provide an explicit error message / validation check explaining the limitation

**Comment by RandomOakForest** [comment]
Thank you for posting this. The team will review it.

**Comment by CAI23sbP** [comment]
@RandomOakForest 
I solved this problem.
The documentation mentions ["Similar Asset Structuring"](https://isaac-sim.github.io/IsaacLab/main/source/how-to/multi_asset_spawning.html#similar-asset-structuring),
so I added a few classes to solve this problem.

The result is this:
Even though the USD is different for each environment, we still use the clone method.
That is, if the USD is the same across environments, we clone it.

https://github.com/user-attachments/assets/dc1975dc-94ab-4462-aaf3-1a32b938ba8e

**Comment by RandomOakForest** [comment]
Great. Would you like to post a show-and-tell in our [_Discussions_](https://github.com/isaac-sim/IsaacLab/discussions)?
